-- ============================================
-- COMPLETE MIGRATION: Fix user_id Type Mismatch (TEXT → UUID)
-- ============================================
-- Generated by: Supabase AI Assistant
-- Purpose: Convert all user_id columns from TEXT to UUID and recreate RLS policies
--
-- CRITICAL: This is a DESTRUCTIVE migration. Follow all steps carefully!
--
-- REQUIREMENTS:
-- 1. FULL DATABASE BACKUP before running
-- 2. ALL user_id values must be valid UUID strings
-- 3. Run in a maintenance window (brief downtime)
-- 4. Save policy export output BEFORE proceeding
--
-- RUN THIS ONLY IF:
-- - You're getting "operator does not exist: text = uuid" errors
-- - Your projects.user_id column is currently TEXT type
-- - You've confirmed all user_id values are valid UUIDs
--
-- ============================================
-- MULTI-STEP PROCESS (DO NOT SKIP STEPS!)
-- ============================================

-- ============================================
-- STEP 1: PRE-FLIGHT VALIDATION
-- ============================================
-- Run this query FIRST and review results
-- If this returns ANY rows, you have invalid UUIDs and CANNOT proceed
-- Fix invalid user_id values before continuing

SELECT 'projects' as table_name, user_id, 'INVALID UUID' as issue
FROM projects
WHERE user_id IS NOT NULL
  AND user_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
UNION ALL
SELECT 'messages', user_id, 'INVALID UUID'
FROM messages
WHERE user_id IS NOT NULL
  AND user_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
UNION ALL
SELECT 'references', user_id, 'INVALID UUID'
FROM "references"
WHERE user_id IS NOT NULL
  AND user_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
UNION ALL
SELECT 'document_folders', user_id, 'INVALID UUID'
FROM document_folders
WHERE user_id IS NOT NULL
  AND user_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
UNION ALL
SELECT 'documents', user_id, 'INVALID UUID'
FROM documents
WHERE user_id IS NOT NULL
  AND user_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
LIMIT 10;

-- EXPECTED RESULT: 0 rows (empty result set)
-- IF YOU SEE ROWS: Stop! Fix those user_id values before proceeding

-- ============================================
-- STEP 2: EXPORT EXISTING POLICIES (BACKUP)
-- ============================================
-- Run this query and SAVE THE OUTPUT to a file (e.g., policies_backup.sql)
-- You'll need this to rollback if something goes wrong

SELECT
  'CREATE POLICY ' || quote_ident(pol.polname) ||
  ' ON ' || quote_ident(nsp.nspname) || '.' || quote_ident(cls.relname) ||
  ' FOR ' ||
    CASE pol.polcmd
      WHEN 'r' THEN 'SELECT'
      WHEN 'a' THEN 'INSERT'
      WHEN 'w' THEN 'UPDATE'
      WHEN 'd' THEN 'DELETE'
      WHEN '*' THEN 'ALL'
    END ||
  COALESCE(' TO ' || array_to_string(ARRAY(
    SELECT rolname FROM pg_roles WHERE oid = ANY(pol.polroles)
  ), ','), ' PUBLIC') ||
  COALESCE(' USING (' || pg_get_expr(pol.polqual, pol.polrelid) || ')', '') ||
  COALESCE(' WITH CHECK (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')', '') ||
  ';' AS policy_ddl
FROM pg_policy pol
JOIN pg_class cls ON cls.oid = pol.polrelid
JOIN pg_namespace nsp ON nsp.oid = cls.relnamespace
WHERE nsp.nspname = 'public'
  AND cls.relname IN ('projects','messages','references','document_folders','documents','agent_activity')
ORDER BY cls.relname, pol.polname;

-- SAVE THIS OUTPUT BEFORE PROCEEDING!

-- ============================================
-- STEP 3: DROP EXISTING BROKEN POLICIES
-- ============================================
-- These policies will break after column type changes
-- Adjust policy names if your database uses different names

ALTER TABLE public.agent_activity DROP POLICY IF EXISTS users_select_activity_from_own_projects;
ALTER TABLE public.document_folders DROP POLICY IF EXISTS delete_document_folders;
ALTER TABLE public.document_folders DROP POLICY IF EXISTS insert_document_folders;
ALTER TABLE public.document_folders DROP POLICY IF EXISTS select_document_folders;
ALTER TABLE public.document_folders DROP POLICY IF EXISTS update_document_folders;
ALTER TABLE public.documents DROP POLICY IF EXISTS delete_documents;
ALTER TABLE public.documents DROP POLICY IF EXISTS insert_documents;
ALTER TABLE public.documents DROP POLICY IF EXISTS select_documents;
ALTER TABLE public.documents DROP POLICY IF EXISTS update_documents;
ALTER TABLE public.messages DROP POLICY IF EXISTS users_insert_messages_to_own_projects;
ALTER TABLE public.messages DROP POLICY IF EXISTS users_select_messages_from_own_projects;
ALTER TABLE public.projects DROP POLICY IF EXISTS users_delete_own_projects;
ALTER TABLE public.projects DROP POLICY IF EXISTS users_insert_own_projects;
ALTER TABLE public.projects DROP POLICY IF EXISTS users_select_own_projects;
ALTER TABLE public.projects DROP POLICY IF EXISTS users_update_own_projects;
ALTER TABLE public."references" DROP POLICY IF EXISTS users_delete_own_references;
ALTER TABLE public."references" DROP POLICY IF EXISTS users_insert_references_to_own_projects;
ALTER TABLE public."references" DROP POLICY IF EXISTS users_select_references_from_own_projects;
ALTER TABLE public."references" DROP POLICY IF EXISTS users_update_own_references;

-- ============================================
-- STEP 4: DISABLE RLS (Defensive)
-- ============================================

ALTER TABLE public.projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."references" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_folders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_activity DISABLE ROW LEVEL SECURITY;

-- ============================================
-- STEP 5: CONVERT COLUMNS (TEXT → UUID)
-- ============================================
-- This is the core migration - converts all user_id columns

-- projects.user_id
ALTER TABLE public.projects
  ALTER COLUMN user_id TYPE uuid USING user_id::uuid;

-- messages.user_id (nullable)
ALTER TABLE public.messages
  ALTER COLUMN user_id TYPE uuid USING (
    CASE WHEN user_id IS NULL THEN NULL ELSE user_id::uuid END
  );

-- references.user_id
ALTER TABLE public."references"
  ALTER COLUMN user_id TYPE uuid USING user_id::uuid;

-- document_folders.user_id
ALTER TABLE public.document_folders
  ALTER COLUMN user_id TYPE uuid USING user_id::uuid;

-- documents.user_id
ALTER TABLE public.documents
  ALTER COLUMN user_id TYPE uuid USING user_id::uuid;

-- ============================================
-- STEP 6: RECREATE RLS POLICIES (WITH UUID CASTING)
-- ============================================
-- Creates fresh policies that work with UUID columns
-- Note: (auth.uid())::uuid cast is now redundant but explicit

-- PROJECTS POLICIES
CREATE POLICY users_select_own_projects
  ON public.projects
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY users_insert_own_projects
  ON public.projects
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY users_update_own_projects
  ON public.projects
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY users_delete_own_projects
  ON public.projects
  FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- MESSAGES POLICIES
CREATE POLICY users_select_messages_from_own_projects
  ON public.messages
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = messages.project_id AND p.user_id = auth.uid()
    )
  );

CREATE POLICY users_insert_messages_to_own_projects
  ON public.messages
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = messages.project_id AND p.user_id = auth.uid()
    )
  );

-- REFERENCES POLICIES
CREATE POLICY users_select_references_from_own_projects
  ON public."references"
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = "references".project_id AND p.user_id = auth.uid()
    )
  );

CREATE POLICY users_insert_references_to_own_projects
  ON public."references"
  FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = "references".project_id AND p.user_id = auth.uid()
    )
  );

CREATE POLICY users_update_own_references
  ON public."references"
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY users_delete_own_references
  ON public."references"
  FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- DOCUMENT_FOLDERS POLICIES
CREATE POLICY select_document_folders
  ON public.document_folders
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY insert_document_folders
  ON public.document_folders
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY update_document_folders
  ON public.document_folders
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY delete_document_folders
  ON public.document_folders
  FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- DOCUMENTS POLICIES
CREATE POLICY select_documents
  ON public.documents
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY insert_documents
  ON public.documents
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY update_documents
  ON public.documents
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY delete_documents
  ON public.documents
  FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- AGENT_ACTIVITY POLICIES
CREATE POLICY users_select_activity_from_own_projects
  ON public.agent_activity
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = agent_activity.project_id AND p.user_id = auth.uid()
    )
  );

-- ============================================
-- STEP 7: RE-ENABLE RLS
-- ============================================

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."references" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_activity ENABLE ROW LEVEL SECURITY;

-- ============================================
-- STEP 8: VERIFICATION
-- ============================================
-- Verify all columns are now UUID type

SELECT
  'projects' as table_name,
  data_type,
  CASE WHEN data_type = 'uuid' THEN '✓ SUCCESS' ELSE '✗ FAILED' END as status
FROM information_schema.columns
WHERE table_name = 'projects' AND column_name = 'user_id'
UNION ALL
SELECT 'messages', data_type,
  CASE WHEN data_type = 'uuid' THEN '✓ SUCCESS' ELSE '✗ FAILED' END
FROM information_schema.columns
WHERE table_name = 'messages' AND column_name = 'user_id'
UNION ALL
SELECT 'references', data_type,
  CASE WHEN data_type = 'uuid' THEN '✓ SUCCESS' ELSE '✗ FAILED' END
FROM information_schema.columns
WHERE table_name = 'references' AND column_name = 'user_id'
UNION ALL
SELECT 'document_folders', data_type,
  CASE WHEN data_type = 'uuid' THEN '✓ SUCCESS' ELSE '✗ FAILED' END
FROM information_schema.columns
WHERE table_name = 'document_folders' AND column_name = 'user_id'
UNION ALL
SELECT 'documents', data_type,
  CASE WHEN data_type = 'uuid' THEN '✓ SUCCESS' ELSE '✗ FAILED' END
FROM information_schema.columns
WHERE table_name = 'documents' AND column_name = 'user_id';

-- EXPECTED: All rows show 'uuid' type and '✓ SUCCESS'

-- Verify policies were recreated
SELECT
  tablename,
  COUNT(*) as policy_count
FROM pg_policies
WHERE schemaname = 'public'
  AND tablename IN ('projects','messages','references','document_folders','documents','agent_activity')
GROUP BY tablename
ORDER BY tablename;

-- EXPECTED:
-- projects: 4 policies
-- messages: 2 policies
-- references: 4 policies
-- document_folders: 4 policies
-- documents: 4 policies
-- agent_activity: 1 policy

-- ============================================
-- MIGRATION COMPLETE!
-- ============================================
-- If all verification checks pass:
-- ✓ All user_id columns are now UUID type
-- ✓ All RLS policies recreated with correct types
-- ✓ Database is ready for production
--
-- If anything failed:
-- 1. Review error messages
-- 2. Check saved policy backup from Step 2
-- 3. Restore from database backup if needed
-- ============================================
