-- ============================================
-- MIGRATION 009: MESSAGE EMBEDDINGS
-- ============================================
-- Purpose: Add vector embeddings to messages for semantic search
-- This enables smart context selection when generating documents

-- Enable pgvector extension for vector similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column to messages
-- Using 1536 dimensions for OpenAI text-embedding-3-small model
ALTER TABLE messages
ADD COLUMN IF NOT EXISTS embedding vector(1536);

-- Create index for fast similarity search using cosine distance
-- This allows efficient nearest neighbor queries
CREATE INDEX IF NOT EXISTS messages_embedding_idx
ON messages
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Add embedding metadata columns
ALTER TABLE messages
ADD COLUMN IF NOT EXISTS embedding_model VARCHAR(100),
ADD COLUMN IF NOT EXISTS embedding_generated_at TIMESTAMP WITH TIME ZONE;

-- Create a helper function to find semantically similar messages
CREATE OR REPLACE FUNCTION find_similar_messages(
  query_embedding vector(1536),
  project_id_filter UUID,
  similarity_threshold FLOAT DEFAULT 0.7,
  max_results INT DEFAULT 20
)
RETURNS TABLE (
  id UUID,
  content TEXT,
  role VARCHAR(20),
  created_at TIMESTAMP WITH TIME ZONE,
  similarity FLOAT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    m.id,
    m.content,
    m.role,
    m.created_at,
    1 - (m.embedding <=> query_embedding) AS similarity
  FROM messages m
  WHERE
    m.project_id = project_id_filter
    AND m.embedding IS NOT NULL
    AND 1 - (m.embedding <=> query_embedding) >= similarity_threshold
  ORDER BY m.embedding <=> query_embedding
  LIMIT max_results;
END;
$$ LANGUAGE plpgsql;

-- Create function to prioritize messages with citations
CREATE OR REPLACE FUNCTION find_relevant_messages_for_document(
  query_embedding vector(1536),
  project_id_filter UUID,
  max_results INT DEFAULT 50
)
RETURNS TABLE (
  id UUID,
  content TEXT,
  role VARCHAR(20),
  created_at TIMESTAMP WITH TIME ZONE,
  has_citation BOOLEAN,
  relevance_score FLOAT
) AS $$
BEGIN
  RETURN QUERY
  WITH scored_messages AS (
    SELECT
      m.id,
      m.content,
      m.role,
      m.created_at,
      EXISTS(
        SELECT 1 FROM projects p
        WHERE p.id = project_id_filter
        AND p.items @> jsonb_build_array(
          jsonb_build_object('citation', jsonb_build_object('messageId', m.id::text))
        )
      ) AS has_citation,
      1 - (m.embedding <=> query_embedding) AS semantic_similarity
    FROM messages m
    WHERE
      m.project_id = project_id_filter
      AND m.embedding IS NOT NULL
      AND m.role = 'user' -- Prioritize user messages
  )
  SELECT
    sm.id,
    sm.content,
    sm.role,
    sm.created_at,
    sm.has_citation,
    -- Boost score for messages with citations (multiply by 1.5)
    CASE
      WHEN sm.has_citation THEN sm.semantic_similarity * 1.5
      ELSE sm.semantic_similarity
    END AS relevance_score
  FROM scored_messages sm
  WHERE sm.semantic_similarity >= 0.6 -- Minimum similarity threshold
  ORDER BY relevance_score DESC
  LIMIT max_results;
END;
$$ LANGUAGE plpgsql;

-- Add comment explaining the embedding column
COMMENT ON COLUMN messages.embedding IS
'Vector embedding (1536 dimensions) generated by OpenAI text-embedding-3-small model for semantic search';

COMMENT ON COLUMN messages.embedding_model IS
'Name of the embedding model used (e.g., text-embedding-3-small)';

COMMENT ON COLUMN messages.embedding_generated_at IS
'Timestamp when the embedding was generated';

-- Row Level Security policies for embeddings (same as parent table)
-- Embeddings inherit the same access control as their messages
-- No additional policies needed since they're part of messages table
